Package.describe({
  name: "ssadams11:meteor-sigma",
  summary: "Sigma is a library dedicated to graph drawing.  Forked from uzumaxy:meteor-sigma 1.0.3 to create a non-minified version to allow sigma.js debugging and enhancement",
  version: "1.0.4",
  git: "https://github.com/ssadams11/meteor-sigma"
});

Package.onUse(function(api) {

  api.addFiles([
  'sigma-src/src/sigma.core.js',
  'sigma-src/src/conrad.js',
  'sigma-src/src/utils/sigma.utils.js',
  'sigma-src/src/utils/sigma.polyfills.js',
  'sigma-src/src/sigma.settings.js',
  'sigma-src/src/classes/sigma.classes.dispatcher.js',
  'sigma-src/src/classes/sigma.classes.configurable.js',
  'sigma-src/src/classes/sigma.classes.graph.js',
  'sigma-src/src/classes/sigma.classes.camera.js',
  'sigma-src/src/classes/sigma.classes.quad.js',
  'sigma-src/src/classes/sigma.classes.edgequad.js',
  'sigma-src/src/captors/sigma.captors.mouse.js',
  'sigma-src/src/captors/sigma.captors.touch.js',
  'sigma-src/src/renderers/sigma.renderers.canvas.js',
  'sigma-src/src/renderers/sigma.renderers.webgl.js',
  'sigma-src/src/renderers/sigma.renderers.svg.js',
  'sigma-src/src/renderers/sigma.renderers.def.js',
  'sigma-src/src/renderers/webgl/sigma.webgl.nodes.def.js',
  'sigma-src/src/renderers/webgl/sigma.webgl.nodes.fast.js',
  'sigma-src/src/renderers/webgl/sigma.webgl.edges.def.js',
  'sigma-src/src/renderers/webgl/sigma.webgl.edges.fast.js',
  'sigma-src/src/renderers/webgl/sigma.webgl.edges.arrow.js',
  'sigma-src/src/renderers/canvas/sigma.canvas.labels.def.js',
  'sigma-src/src/renderers/canvas/sigma.canvas.hovers.def.js',
  'sigma-src/src/renderers/canvas/sigma.canvas.nodes.def.js',
  'sigma-src/src/renderers/canvas/sigma.canvas.edges.def.js',
  'sigma-src/src/renderers/canvas/sigma.canvas.edges.curve.js',
  'sigma-src/src/renderers/canvas/sigma.canvas.edges.arrow.js',
  'sigma-src/src/renderers/canvas/sigma.canvas.edges.curvedArrow.js',
  'sigma-src/src/renderers/canvas/sigma.canvas.edgehovers.def.js',
  'sigma-src/src/renderers/canvas/sigma.canvas.edgehovers.curve.js',
  'sigma-src/src/renderers/canvas/sigma.canvas.edgehovers.arrow.js',
  'sigma-src/src/renderers/canvas/sigma.canvas.edgehovers.curvedArrow.js',
  'sigma-src/src/renderers/canvas/sigma.canvas.extremities.def.js',
  'sigma-src/src/renderers/svg/sigma.svg.utils.js',
  'sigma-src/src/renderers/svg/sigma.svg.nodes.def.js',
  'sigma-src/src/renderers/svg/sigma.svg.edges.def.js',
  'sigma-src/src/renderers/svg/sigma.svg.edges.curve.js',
  'sigma-src/src/renderers/svg/sigma.svg.labels.def.js',
  'sigma-src/src/renderers/svg/sigma.svg.hovers.def.js',
  'sigma-src/src/middlewares/sigma.middlewares.rescale.js',
  'sigma-src/src/middlewares/sigma.middlewares.copy.js',
  'sigma-src/src/misc/sigma.misc.animation.js',
  'sigma-src/src/misc/sigma.misc.bindEvents.js',
  'sigma-src/src/misc/sigma.misc.bindDOMEvents.js',
  'sigma-src/src/misc/sigma.misc.drawHovers.js',
      //plugins next...
    'sigma-src/plugins/sigma.layout.forceAtlas2/worker.js',
    'sigma-src/plugins/sigma.layout.forceAtlas2/supervisor.js',
    'sigma-src/plugins/sigma.plugins.dragNodes/sigma.plugins.dragNodes.js',
    'sigma-src/plugins/sigma.exporters.svg/sigma.exporters.svg.js',
    'sigma-src/plugins/sigma.parsers.gexf/gexf-parser.js',
    'sigma-src/plugins/sigma.parsers.gexf/sigma.parsers.gexf.js',
    'sigma-src/plugins/sigma.parsers.json/sigma.parsers.json.js',
    'sigma-src/plugins/sigma.pathfinding.astar/sigma.pathfinding.astar.js',
    'sigma-src/plugins/sigma.plugins.animate/sigma.plugins.animate.js',
    'sigma-src/plugins/sigma.plugins.filter/sigma.plugins.filter.js',
    'sigma-src/plugins/sigma.plugins.neighborhoods/sigma.plugins.neighborhoods.js',
    'sigma-src/plugins/sigma.plugins.relativeSize/sigma.plugins.relativeSize.js',
    'sigma-src/plugins/sigma.renderers.customEdgeShapes/sigma.canvas.edgehovers.dashed.js',
    'sigma-src/plugins/sigma.renderers.customEdgeShapes/sigma.canvas.edgehovers.dotted.js',
    'sigma-src/plugins/sigma.renderers.customEdgeShapes/sigma.canvas.edgehovers.parallel.js',
    'sigma-src/plugins/sigma.renderers.customEdgeShapes/sigma.canvas.edgehovers.tapered.js',
    'sigma-src/plugins/sigma.renderers.customEdgeShapes/sigma.canvas.edges.dashed.js',
    'sigma-src/plugins/sigma.renderers.customEdgeShapes/sigma.canvas.edges.dotted.js',
    'sigma-src/plugins/sigma.renderers.customEdgeShapes/sigma.canvas.edges.parallel.js',
    'sigma-src/plugins/sigma.renderers.customEdgeShapes/sigma.canvas.edges.tapered.js',
    'sigma-src/plugins/sigma.renderers.customShapes/shape-library.js',
    'sigma-src/plugins/sigma.renderers.customShapes/sigma.renderers.customShapes.js',
    'sigma-src/plugins/sigma.renderers.edgeLabels/settings.js',
    'sigma-src/plugins/sigma.renderers.edgeLabels/sigma.canvas.edges.labels.curve.js',
    'sigma-src/plugins/sigma.renderers.edgeLabels/sigma.canvas.edges.labels.curvedArrow.js',
    'sigma-src/plugins/sigma.renderers.edgeLabels/sigma.canvas.edges.labels.def.js',
    'sigma-src/plugins/sigma.renderers.snapshot/sigma.renderers.snapshot.js',
    'sigma-src/plugins/sigma.statistics.HITS/sigma.statistics.HITS.js'
  ], ["client"]);
});